[general]
static = yes
writeprotect = no
autofallthrough = yes
clearglobalvars = no

[globals]

[auto-dialer]
exten => _X.,1,NoOp(Robocall originate dst=${EXTEN} batch=${BATCH} cont=${CONT})
 same => n,Set(CDR(type)=out-ivr)
 same => n,Set(CDR(userfield)=${BATCH})
 same => n,Set(CDR(accountcode)=${BATCH})
 same => n,Goto(${CONT},1000,1)

[demo-ivr]
exten => 1000,1,NoOp(Demo IVR for batch ${BATCH})
 same => n,Answer()
 same => n,Wait(2)
 same => n,Hangup()

[agent-demo]
exten => 1000,1,NoOp(Demo queue member)
 same => n,Answer()
 same => n,Wait(10)
 same => n,Hangup()
