[general]
enabled = yes
webenabled = no
port = 5038
bindaddr = 0.0.0.0
displayconnects = yes
allowmultiplelogin = yes

[amiuser]
secret = change-me
deny = 0.0.0.0/0.0.0.0
permit = 0.0.0.0/0.0.0.0
read = system,call,log,verbose,command,agent,user,reporting,cdr,dialplan
write = system,call,log,verbose,command,agent,user,reporting,cdr,dialplan,originate

[oami]
secret = change-me
deny = 0.0.0.0/0.0.0.0
permit = 0.0.0.0/0.0.0.0
read = system,call,log,verbose,command,agent,user,reporting,cdr,dialplan
write = system,call,log,verbose,command,agent,user,reporting,cdr,dialplan,originate
